# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tank/nixos";
      fsType = "zfs";
    };

  fileSystems."/boot1" =
    { device = "/dev/disk/by-uuid/2F17-BB7E";
      fsType = "vfat";
    };

  fileSystems."/boot2" =
    { device = "/dev/disk/by-uuid/2F18-88C4";
      fsType = "vfat";
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/zvol/tank/nixos/docker";
      fsType = "ext4";
    };

  fileSystems."/var/lib/rancher" =
    { device = "/dev/zvol/tank/nixos/rancher";
      fsType = "ext4";
    };

  fileSystems."/opt/faf" =
    { device = "tank/faf";
      fsType = "zfs";
    };

  fileSystems."/opt/faf/data/faf-db" =
    { device = "tank/faf/mariadb";
      fsType = "zfs";
    };

  fileSystems."/opt/faf/data/legacy-featured-mod-files" =
    { device = "tank/faf/legacy-featured-mod-files";
      fsType = "zfs";
    };

  fileSystems."/opt/faf/data/maps" =
    { device = "tank/faf/maps";
      fsType = "zfs";
    };

  fileSystems."/opt/faf/data/mods" =
    { device = "tank/faf/mods";
      fsType = "zfs";
    };

  fileSystems."/opt/faf/data/phpbb3" =
    { device = "tank/faf/phpbb3";
      fsType = "zfs";
    };

  fileSystems."/opt/faf/data/nodebb" =
    { device = "tank/faf/nodebb";
      fsType = "zfs";
    };

  fileSystems."/opt/faf/data/mongodb" =
    { device = "tank/faf/mongodb";
      fsType = "zfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
