# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tank";
      fsType = "zfs";
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/zvol/tank/docker";
      fsType = "ext4";
    };

  fileSystems."/opt/faf" =
    { device = "tank/fafstack";
      fsType = "zfs";
    };

  fileSystems."/opt/faf/data/faf-db" =
    { device = "tank/mysql";
      fsType = "zfs";
    };

  fileSystems."/opt/faf/data/faf-mongodb" =
    { device = "tank/mongodb";
      fsType = "zfs";
    };

  fileSystems."/opt/faf/data/content/replays" =
    { device = "tank/replays";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 16;
}
