name: Syntax Test 

# Controls when the action will run. 
on:
  pull_request:
  push:

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: find  -name *.nix -exec nix-instantiate --parse  {} \;
